# Generated by Django 3.2.4 on 2021-06-20 22:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('order_no', models.CharField(max_length=15, unique=True)),
                ('reference', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=300)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_draft', models.BooleanField()),
                ('saved_draft_at', models.DateTimeField()),
                ('saved_submitted', models.BooleanField()),
                ('saved_submitted_at', models.DateTimeField()),
                ('approved', models.BooleanField()),
                ('approved_at', models.DateTimeField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('account', models.CharField(max_length=500)),
                ('tax_rate', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=80)),
                ('sub_total', models.DecimalField(decimal_places=4, max_digits=16)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=1000)),
                ('attention', models.CharField(max_length=500)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('instructions', models.CharField(max_length=800)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorder')),
            ],
        ),
    ]
